# Generated by Django 3.2.5 on 2022-02-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularContentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='文章標題')),
                ('content', models.TextField(verbose_name='文章內容')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='PopularContentSourceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.IntegerField(choices=[(0, '影像'), (1, 'Video')], verbose_name='資源類型')),
                ('source_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='資源名稱')),
                ('source_path', models.URLField(max_length=512, verbose_name='資源位置')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('popular_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popular_content.popularcontentmodels', verbose_name='文章ID')),
            ],
        ),
    ]
