# Generated by Django 3.2.5 on 2022-02-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularContentModels',
            new_name='PopularContent',
        ),
        migrations.RenameModel(
            old_name='PopularContentSourceModels',
            new_name='PopularContentSource',
        ),
    ]
